/* ============================= PORTFOLIO INTERACTIONS ============================= */
const reduceMotion=window.matchMedia('(prefers-reduced-motion: reduce)').matches;
const glow=document.querySelector('.cursor-glow');
if(glow)window.addEventListener('pointermove',({clientX,clientY})=>{glow.style.left=`${clientX}px`;glow.style.top=`${clientY}px`},{passive:true});
const liveDate=document.querySelector('#live-date'),liveTime=document.querySelector('#live-time');
const updateClock=()=>{const now=new Date();if(liveDate)liveDate.textContent=new Intl.DateTimeFormat(undefined,{weekday:'short',day:'2-digit',month:'short',year:'numeric'}).format(now);if(liveTime)liveTime.textContent=new Intl.DateTimeFormat(undefined,{hour:'2-digit',minute:'2-digit',second:'2-digit',hour12:false}).format(now)};updateClock();setInterval(updateClock,1000);
document.querySelectorAll('a[href^="#"]').forEach(link=>link.addEventListener('click',event=>{const target=document.querySelector(link.getAttribute('href'));if(!target)return;event.preventDefault();target.scrollIntoView({behavior:reduceMotion?'auto':'smooth',block:'start'});}));
if(!reduceMotion){const style=document.createElement('style');style.textContent=`.reveal{opacity:0;transform:translateY(28px);transition:opacity .7s ease,transform .7s cubic-bezier(.2,.7,.2,1)}.reveal.is-visible{opacity:1;transform:none}.reveal.delay-1{transition-delay:.12s}.scroll-progress{position:fixed;top:0;left:0;width:100%;height:3px;transform-origin:left;transform:scaleX(0);z-index:99999;background:#71f5bf;box-shadow:0 0 14px rgba(113,245,191,.7);pointer-events:none}.toolkit-focus{border-color:rgba(113,245,191,.65)!important;box-shadow:0 25px 65px rgba(113,245,191,.12),0 0 0 1px rgba(113,245,191,.08)}`;document.head.appendChild(style);const progress=document.createElement('div');progress.className='scroll-progress';document.body.appendChild(progress);const updateProgress=()=>{const max=document.documentElement.scrollHeight-innerHeight;progress.style.transform=`scaleX(${max>0?scrollY/max:0})`};addEventListener('scroll',updateProgress,{passive:true});addEventListener('resize',updateProgress,{passive:true});updateProgress();const observer=new IntersectionObserver(entries=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('is-visible');observer.unobserve(entry.target)}}),{threshold:.08,rootMargin:'0px 0px -40px'});document.querySelectorAll('.reveal').forEach(el=>observer.observe(el));
const role=document.querySelector('.typing-role'),text=role?.querySelector('.typing-text');if(role&&text){const roles=['Full Stack Developer','React Developer','AI / IoT Builder','Problem Solver'];let ri=0,ci=0,del=false;const type=()=>{const word=roles[ri];text.textContent=word.slice(0,ci);if(!del){if(ci<word.length){ci++;setTimeout(type,68)}else{del=true;setTimeout(type,1450)}}else if(ci>0){ci--;setTimeout(type,38)}else{del=false;ri=(ri+1)%roles.length;setTimeout(type,300)}};type()}
document.querySelectorAll('[data-tilt]').forEach(card=>{const max=Number(card.dataset.tiltMax||5);card.addEventListener('pointermove',e=>{const r=card.getBoundingClientRect(),x=(e.clientX-r.left)/r.width-.5,y=(e.clientY-r.top)/r.height-.5;card.style.transform=`perspective(900px) rotateX(${(-y*max).toFixed(2)}deg) rotateY(${(x*max).toFixed(2)}deg) translateZ(3px)`});card.addEventListener('pointerleave',()=>card.style.transform='')});
/* Seamless finite-loop toolkit. Each item reaches center, stays highlighted 2.5s, then advances. */
const toolkit=document.querySelector('[data-stack-marquee]'),track=toolkit?.querySelector('.stack-track');if(toolkit&&track){const original=[...track.children];original.forEach(card=>track.appendChild(card.cloneNode(true)));toolkit.style.overflow='hidden';track.style.transition='transform .85s cubic-bezier(.22,.7,.2,1)';let index=0,busy=false;const cards=()=>[...track.children];const center=()=>{const c=cards()[index];if(!c)return;track.style.transform=`translateX(${toolkit.clientWidth/2-(c.offsetLeft+c.offsetWidth/2)}px)`;cards().forEach((x,i)=>{const d=Math.abs(i-index);x.classList.toggle('toolkit-focus',i===index);x.style.opacity=d===0?'1':d===1?'.68':'.38';x.style.transform=d===0?'translateY(-10px) scale(1.08)':d===1?'scale(.94)':'scale(.86)'})};const advance=()=>{if(busy)return;busy=true;index++;center();setTimeout(()=>{if(index>=original.length){track.style.transition='none';index=0;center();void track.offsetWidth;track.style.transition='transform .85s cubic-bezier(.22,.7,.2,1)'}busy=false},2500)};center();setInterval(advance,4200);addEventListener('resize',center)}}